# docker-compose.yml

version: "3"

volumes:
  prometheus_data:

networks:
  observability:

services:
  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    networks:
      - observability

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9320:9320
    networks:
      - observability